using UnityEngine;

using ZL.CS.Singleton;

namespace ZL.Unity.Singleton
{
    [DisallowMultipleComponent]

    public abstract class MonoSingleton<TMonoSingleton> : MonoBehaviour, ISingleton<TMonoSingleton>

        where TMonoSingleton : MonoSingleton<TMonoSingleton>
    {
        public static TMonoSingleton Instance => ISingleton<TMonoSingleton>.Instance;

        protected virtual void Awake()
        {
            ISingleton<TMonoSingleton>.TrySetInstance((TMonoSingleton)this);
        }

        protected virtual void OnDestroy()
        {
            ISingleton<TMonoSingleton>.Release((TMonoSingleton)this);
        }
    }
}